### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [android-nuc/MusicPlayer#1]
Hello. I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project.

**Comment by InnoFang** [comment]
hi @mirzazulfan ,
I am the author of this project and I'm glad that you are interested in this project, but this project is the code that I shared my Android development practice with my classmates. In the other word, it is experimental, so it isn't formally put on the App Store and the logo is not required. Thanks for your proposal very much.
